# Generated by Django 4.2.7 on 2023-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datacompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
